models: [xgboost]

ridge:
  type: ridge
  alpha: [0., 0.01, 0.1, 0.5, 1., 2., 10.]
  feature_slots: [neighbourhood_name, property_type_name, room_type_name, bed_type_name, accommodates, bathrooms, bedrooms, beds, minimum_nights, longitude_to_center, latitude_to_center, distance_to_center]

xgboost:
  type: xgboost
  max_depth: [4, 6]
  lambda: [1.]
  alpha: [0., 0.2]
  n_estimators: [300, 30]
  feature_slots: [neighbourhood_name, property_type_name, room_type_name, bed_type_name, accommodates, bathrooms, bedrooms, beds, minimum_nights, longitude_to_center, latitude_to_center, distance_to_center]

mlp:
  type: mlp
  hidden_layer_sizes: [[50], [100], [100, 50]]
  activation: [relu, tanh]
  alpha: [0.001, 0.01]
  learning_rate_init: [0.001, 0.01]
  max_iter: [500]
  early_stopping: [true]
  validation_fraction: [0.1]
  n_iter_no_change: [30]
  random_state: [42]
  feature_slots: [neighbourhood_name, property_type_name, room_type_name, bed_type_name, accommodates, bathrooms, bedrooms, beds, minimum_nights, longitude_to_center, latitude_to_center, distance_to_center]

params:
  data_path: data/raw.parquet
  seed: 42
  num_bootstrap: 1000
  test_size: 0.3
  output_path: models/model.joblib